apiVersion: apps/v1
kind: Deployment
metadata:
  name: <<NAME>>
  labels:
    app: <<NAME>>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <<NAME>>
  template:
    metadata:
      labels:
        app: <<NAME>>
    spec:
      containers:
        - name: <<NAME>>
          image: registry.digitalocean.com/omnitemplate-registry/<<NAME>>:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
          - secretRef:
              name: omnigraph-secrets
          env:
          - name: PACKAGE_NAME
            value: <<NAME>>